package Muhtar_SDET.Day43_CollectionsAndMaps.enums;

public enum Day {
     // JUST ACCEPTS DATA WHICH YOU DECLARED
    // ENUM IS THE BEST DATATYPE TO USE WHENEVER YOU HAVE FIXED SET OF CONSTANT,
    // WHENEVER YOU HAVE NUMBER OF THINGS

    MONDAY,
    TUESDAY,
    WEDNESDAY,
    THURSDAY,
    FRIDAY,
    SATURDAY,
    SUNDAY
}
